/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "counter.v:1.1-14.10" *)
module counter(clk, reset, count);
  (* src = "counter.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.16-3.21" *)
  input reset;
  wire reset;
  (* src = "counter.v:4.22-4.27" *)
  output [7:0] count;
  reg [7:0] count;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "7" *)
  wire [31:0] _00_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [31:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "8" *)
  wire [31:0] _02_;
  (* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _03_;
  (* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _04_;
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[0] <= 1'h0;
    else count[0] <= _01_[0];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[1] <= 1'h0;
    else count[1] <= _02_[1];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[2] <= 1'h0;
    else count[2] <= _02_[2];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[3] <= 1'h0;
    else count[3] <= _02_[3];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[4] <= 1'h0;
    else count[4] <= _02_[4];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[5] <= 1'h0;
    else count[5] <= _02_[5];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[6] <= 1'h0;
    else count[6] <= _02_[6];
  (* src = "counter.v:7.1-12.4" *)
  always @(posedge clk, posedge reset)
    if (reset) count[7] <= 1'h0;
    else count[7] <= _02_[7];
  assign _01_[0] = ~count[0];
  assign _02_[5] = count[5] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[4];
  assign _02_[6] = count[6] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[5];
  assign _02_[7] = count[7] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[6];
  assign _00_[1] = count[1] &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _00_[3] = _03_ &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:240.19-240.41" *)  _00_[1];
  assign _03_ = count[3] &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[2];
  assign _04_ = count[5] &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[4];
  assign _00_[5] = _04_ &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[3];
  assign _00_[2] = count[2] &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[1];
  assign _00_[4] = count[4] &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[3];
  assign _00_[6] = count[6] &(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:293.27-293.63|/foss/tools/yosys/bin/../share/yosys/techmap.v:248.19-248.41" *)  _00_[5];
  assign _02_[1] = count[1] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  count[0];
  assign _02_[2] = count[2] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[1];
  assign _02_[3] = count[3] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[2];
  assign _02_[4] = count[4] ^(* src = "counter.v:11.18-11.27|/foss/tools/yosys/bin/../share/yosys/techmap.v:296.13-296.25" *)  _00_[3];
  assign { _00_[31:8], _00_[0] } = { 24'h000000, count[0] };
  assign _01_[31:1] = { 24'h000000, count[7:1] };
  assign { _02_[31:8], _02_[0] } = { 23'h000000, _00_[7], _01_[0] };
endmodule
